- .github/workflows/ci.yml
> Repair ci failure

- .github/workflows/ci.yml
- ossfs/core.py
- tests/conftest.py
- tests/test_file.py
- tests/test_login.py
- tests/test_object.py
- tests/test_ossfs.py
1. A unique path for every test on different versions and platforms.
2. Set the endpoint and test bucket to US.
3. Add env config of endpoint and test bucket
> Unique path for every test

- ossfs/core.py
> Suppress low level log from third party.

- ossfs/core.py
- tests/test_object.py
Fix #7 
1. Add a dynamic block size decorator
2. wrap the open function
> Dynamic block size ajustment at connection error

- ossfs/core.py
- setup.py
- tests/test_file.py
- tests/test_login.py
- tests/test_ossfs.py
> Make address format compatible with other fs.

- ossfs/core.py
- tests/test_object.py
fix #3 
1. support prefix in `ossfs.find`
2. add some test for it
> Support prefix in method `find`

- .github/workflows/ci.yml
> set max parallel for running tests

- .github/workflows/ci.yml
> Set semantic name to each ci tests

- .github/workflows/ci.yml
- ossfs/core.py
- tests/test_file.py
- tests/test_object.py
fix #20 
1. add duration log for tests.
> Test Performance optimaztion.

- requirements.txt
- setup.py
- tests/test_ossfs.py
> Follow the version and depends of fsspec

- ossfs/core.py
- tests/test_object.py
> remove deleting object before resumable_upload

- ossfs/core.py
- setup.py
1. Get/put performance optimization.
> Update to 2021.6.2

- ossfs/core.py
- setup.py
1. fix #24 ( The emulator tests is still lacking )
2. Upgrade to 2021.7.0
> Solve the problem caused by emulator

- ossfs/core.py
> Provide a direct way to pipe stream to ossfile

- ossfs/core.py
- tests/test_file.py
- tests/test_object.py
- tests/test_ossfs.py
fix #33
1. reuse of the session object
2. delete some debug prints in tests
> Reuse of session object in the whole ossfs

- ossfs/core.py
> Remove oss-emulator related codes

- tests/test_file.py
- tests/test_object.py
> Use pseudo random data instead of repeated one

- ossfs/core.py
- tests/test_object.py
fix #27 
1. implement dircache of fsspec
> Dir cache for file status.

- ossfs/core.py
- setup.py
> `ls` performance optimization

- ossfs/core.py
- setup.py
for conda release and dvc new progressbar
> Relax oss2 version, bump into 2021.7.5

- ossfs/core.py
- tests/test_login.py
fix #48 
1. get endpoint from OSS_ENDPOINT
2. can set endpoint later using ossfs.set_endpont
> get endpoint url from the environment

- ossfs/core.py
- tests/conftest.py
- tests/test_login.py
- tests/test_object.py
Fix #52 
1. now we can cat the public bucket file from anonymous
> Solve the permission problem

- ossfs/core.py
- ossfs/exceptions.py
- tests/test_file.py
- tests/test_object.py
fix #56 
1. Add a new layer _call_oss to deal with all of the Request Exceptions.
2. Add a new exception translate function.
> Middle layer to manage Request Exceptions

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- ossfs/core.py
- test_requirements.txt
- tests/test_file.py
- tests/test_login.py
- tests/test_object.py
- tests/test_ossfs.py
- Updates GitHub Actions.
- Updates pre-commit hooks
- Updates mypy
- Changes `fs.find()` signature
- `black` formats code
> Test on Python 3.11

- .github/workflows/ci.yml
- setup.py
> Drop python3.6 support

- src/ossfs/core.py
- tests/conftest.py
- tests/test_file.py
- tests/test_login.py
- tests/test_object.py
- tests/test_ossfs.py
fix #84
1. Update anonymous bucket name
2. Add timezone offset for info from OSS
> Update test bucket move to my personal account

- .github/workflows/tests.yml
- tests/conftest.py
1. add a new secret anonymous bucket name to replace the old hard-coded
one.
2. In github ci import this new ENV name.
> Add a new secret anonymous bucket name

- setup.cfg
- src/ossfs/async_oss.py
- src/ossfs/base.py
- src/ossfs/core.py
fix: #90
1. Extract public method from `OSSFileSystem` to `BaseOSSFileSystem`
2. Add a new AioOSSFileSystem.
3. Add aiooss2 to dependency.
> Add class AioOSSFileSystem and  extract public method from `OSSFileSystem` to `BaseOSSFileSystem`

- src/ossfs/__init__.py
- src/ossfs/async_oss.py
- src/ossfs/base.py
- src/ossfs/core.py
- src/ossfs/exceptions.py
- tests/conftest.py
- tests/test_bucket.py
- tests/test_login.py
- tests/test_object.py
fix: #92
1. Implement session operations in AioOSSFileSystem
2. Implement `ls` related operations (ls_dir, ls_bucket)in AioOSSFileSystem
3. Add a new tests to test list bucket
4. Add a new `ls` tests for AioOSSFileSystem
5. Extract similar methods in sync and async ossfs to the base class.
> Implement async version of ls

- src/ossfs/async_oss.py
- src/ossfs/base.py
- src/ossfs/core.py
- src/ossfs/exceptions.py
- tests/test_object.py
fix: #93 
1. Add `rm`,  `rm_file` to `AioOSSFileSystem`
2. Add related tests for `rm` operations.
3. Implement `checksum` and `ukey` for `AioOSSFileSystem`
> Implement `remove` related operations in `AioOSSFileSystem`

- src/ossfs/async_oss.py
- src/ossfs/core.py
- tests/test_object.py
fix: #94
1. Add _cp_file and _copy methods and some tests for it.
2. Add tests for async `mv` and `cp`
> Implement `copy` related operations for  the AysncOSSFileSystem

- src/ossfs/async_oss.py
- src/ossfs/base.py
- src/ossfs/core.py
- src/ossfs/exceptions.py
- src/ossfs/utils.py
- tests/test_login.py
- tests/test_object.py
- tests/test_ossfs.py
fix: #95
1. implement `pipe_file` for the `AioOSSFileSystem`
2. make tests for `pipe_file` passed.
> Implement `pipe` related operations in the `AysncOSSFileSystem`

- tests/bench/test_put_get.py
- tests/conftest.py
- tests/func/test_bucket.py
- tests/func/test_error.py
- tests/func/test_file.py
- tests/func/test_object.py
- tests/func/test_ossfs.py
1. Rewrite the `test_path` fixture.
2. Refactor put all inspect.stack()[1][0].f_code.co_name into a function
> Rewrite test fixture

- src/ossfs/async_oss.py
This un-awaited method will prohibit the uploading of large files. 
Related issues: https://github.com/iterative/dvc/issues/10643
> fix: un-awaited method
